### ISSUE TITLE
Figure out `join()` and `Drop` behavior for `DownloadHandle`

### ISSUE THREAD

**Issue by graebm** [awslabs/aws-s3-transfer-manager-rs#65]
Currently, DownloadHandle has a [join()](https://github.com/awslabs/aws-s3-transfer-manager-rs/blob/3dd20c8aa0872352100cf456beee02bfc53c73d1/aws-s3-transfer-manager/src/operation/download/handle.rs#L45) function, but neither [cp.rs](https://github.com/awslabs/aws-s3-transfer-manager-rs/blob/3dd20c8aa0872352100cf456beee02bfc53c73d1/aws-s3-transfer-manager/examples/cp.rs#L174) or the [benchmark runner](https://github.com/awslabs/aws-crt-s3-benchmarks/blob/71be44d88dff5975fca2caa8a838bc0e6c45cbb7/runners/s3-benchrunner-rust/src/transfer_manager.rs#L94) bother to call it. It was added because `UploadHandle` has a [join()](https://github.com/awslabs/aws-s3-transfer-manager-rs/blob/3dd20c8aa0872352100cf456beee02bfc53c73d1/aws-s3-transfer-manager/src/operation/upload/handle.rs#L55), and we thought the APIs should be similar.

But `DownloadHandle::join()` cancels the download, while `UploadHandle::join()` waits for the upload to successfully complete, and has a separate `UploadHandle::abort()` function. Should we rename ~DownloadHandle::join()~ to `DownloadHandle::abort()`?

Also, what's the `Drop` behavior for `DownloadHandle`? We should probably ensure its spawned tasks get cancelled ASAP. Likewise for `UploadHandle/UploadObjectsHandle/DownloadObjectsHandle`

- [x] Drop and cancel for `UploadHandle/UploadObjectsHandle` ([PR](https://github.com/awslabs/aws-s3-transfer-manager-rs/pull/75))
- [ ] Drop and cancel for `DownloadHandle` ([PR](https://docs.rs/tokio/latest/tokio/task/struct.JoinError.html#method.is_cancelled))
- [x] Drop and cancel for `DownloadObjectsHandle` ([PR](https://github.com/awslabs/aws-s3-transfer-manager-rs/pull/76))

**Comment by ysaito1001** [comment]
This issue can be closed once all subtasks have been completed. As a result of the subtasks, here is a summary:
--- | Join | Abort | Drop
--- | --- | --- | ---
DownloadHandle | there is no `join`, but `drain`consumes the body  | cancels in-progress tasks ASAP |  futures are destroyed at whatever await points
UploadHandle | waits for completion of spawned tasks | ditto  | ditto
DownloadObjectsHandle | waits for completion of spawned tasks  | ditto | ditto
UploadObjectsHandle | waits for completion of spawned tasks  |  ditto | ditto
